/*

RSEngine
Copyright (c) 2020 Mason Lee Back

File name: RSRender_Enums.h

*/

#ifndef _RSRENDER_ENUMS_H_
#define _RSRENDER_ENUMS_H_

namespace rs::Renderer {
	enum RSPrimitiveTopology {
		RS_PRIMITIVE_TOPOLOGY_POINTLIST,
		RS_PRIMITIVE_TOPOLOGY_LINELIST,
		RS_PRIMITIVE_TOPOLOGY_LINESTRIP,
		RS_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
		RS_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP
	};

	enum class RSBufferType {
		VERTEX_BUFFER = D3D11_BIND_VERTEX_BUFFER,
		INDEX_BUFFER = D3D11_BIND_INDEX_BUFFER,
		CONST_BUFFER = D3D11_BIND_CONSTANT_BUFFER,
		COMPUTE_RW_BUFFER = D3D11_BIND_UNORDERED_ACCESS,
		BUFFER_TYPE_UNKNOWN,
		BUFFER_TYPE_COUNT
	};

	enum class RSBufferUsage {
		GPU_READ = D3D11_USAGE_IMMUTABLE,
		GPU_READ_WRITE = D3D11_USAGE_DEFAULT,
		GPU_READ_CPU_WRITE = D3D11_USAGE_DYNAMIC,
		GPU_READ_CPU_READ = D3D11_USAGE_STAGING,
		BUFFER_USAGE_COUNT
	};

	using RSTextureID = int;
	using RSShaderID = int;
	using RSBufferID = int;

	using RSRasterID = int;

	using RSPipelineID = int;
}

#endif // _RSRENDER_ENUMS_H_
